version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\cmake-init
image:
# - Visual Studio 2013
# - Visual Studio 2015
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x86
- x64

environment:
  matrix:
  - arch: Win64

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: |-
    git submodule update --init --recursive
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
    ls
build:
  project: c:\projects\cmake-init\build\a_chaos_64.sln
  verbosity: minimal
  parallel: true
